//  *(`r`n|$)
// (.+?) *(`r`n|$)
// "$1\n"`n`t+ 
//  .,:;i1tfLCG08@

var sandwiches = [
	  "                                            ...:::,,;,,..\n"
	+ "                                         ..::........:::....\n"
	+ "                                    .:;;Lr;,:.,,;;r;;,;;r;rrLrr:\n"
	+ "                                 .:,,;;,....:rr;;r;rr;,r;rrLcLrr7;\n"
	+ "                             .:,;;L;,.. .:;;;;rrr;;;Lrrrr;;rrrr;cr\n"
	+ "                   ..,,;,,,,:,:::,...,;;;r;r;rrLrcrrrcrr;;;;,rLz\n"
	+ "              .:;;rrL;;,;.::,.::,:,:;;rrr;r;rrrrrrL;rrr,;;;rr,,.;;;,;\n"
	+ "           ,,rrLLT;;:::,;rrLrr;;;;;;;rrrrrrrrL;r;Lrr;;;r;rr;:. .,,.;.\n"
	+ "        ,;r;rrrrrrr;rrrLrrr;,;r;;;;;r;rrr;rrr;;;rrnTLr;,:.. .;T:. ,;\n"
	+ "     :,r;r;rrrrcryrcrr;LrL;rrLrrrrrr;rrr;r;;rzyyc171rczTT7;;1j7iZSW7\n"
	+ "   .rrrrr;LLcrzrLLrTzcyz7yTTTrcrLr;:,,;,,;TTnLLTr,;;r:SKKG0KSy1jGN8z.\n"
	+ "  ;r;r;crTyizrLzzTTnzjniyn77zzLLrr;cyjiL:LTr;Lr,rc: ZZ1r;WGSj;rT:ii;\n"
	+ " .7rrrLy77j77yn71zzyj1ny1TyTzz7y2bGGGKb2EyC77zTTEyziWEUWGEyr;LW1:,:\n"
	+ ",rcTzj7in2izz1czL7Lyy7TyLr7nTyr;:riiz1r.jbiCSGO0DWS0gBWG1r,rLT;7L;\n"
	+ "crzTZjKCEC2nizn7inZinc71nLzTL;,.  r::   r7LTO27yr,;;1r,7i;7yr71;.\n"
	+ " rZEnjiUEEbNG8S2r;;;::;r;,   .;,cDGr,, 1bOn;CS1,.:.: ;rr. .rzr\n"
	+ "   ;Gi7bGK7Tr  .,rc,;..   :;17KyG0@$GWBDNEn r;. .;U2zKy,;rT,\n"
	+ "   r$Or;;y    :yU8GOSEZ2OB@@BNSEE2jUjWWNUKC, ;.,;ZnTz7ynr:\n"
	+ "   .ZKE1yrrr2OGUZrTyUb8$@gi8N1Tr;;;;rLbbUb27:;,7Z1j7z;.\n"
	+ "  ;r;GG8D$D$DB8bC$D8OU2NDOcr .;1yrrr  .. .  .;ZKL;.\n"
	+ "  :rb1LrnC2W8UWZ2WUcrr;;, . :rK7LrL;;,L;;rj2Kr:\n"
	+ "   .T;.rr :rr.  .,;;;rrLrrLr.,TjL, ,n2zZ22r.\n"
	+ "    .:;cnz,         .  rU1r::,;rTybSKCy,.\n"
	+ "      .222  ;yLTTrTjyc;rTCCKCUUGWW1;.\n"
	+ "        yWWSNbbESEUjKi2EUSOSSZir,\n"
	+ "          .;L17nTLrTrr;;:.\n"

	, "                     .;jUWSb2j1i1ZKB0$$@$@g$GbiL:\n"
	+ "                  ,yb8DUjcc;::r1SG8G8B0D$0$DgD$g$8Gir\n"
	+ "               .rCSWEnrr;rr;,71Z2KUWbWOGGWOOSObWSWWGG8UT\n"
	+ "             .rcyT1TTr;;yr,Tjn17jZC2bEbUbUb2UZZni1Zy17KSGZ.\n"
	+ "            ,crrrrrLcc;;;:;71nz1Tzyj1nT17n7Z1nzL;r;;;r,,rZbL\n"
	+ "           :r,,,;;;,r;;r.,LrTrr7KjZCbbNGGGNOGWbZKEZzy;r .icyz\n"
	+ "           y;;.:,;;;cnZi;TiG8BUyT2nyzjUGGNB0BUKSO0WKUSS;.2rrGi\n"
	+ "          .,.:cj;    K$SZ:,Z2Tz..:;:..       .,       ;nK   ;.\n"
	+ "              .;.;,;;;:. :;TL,;r;r;zrLrr;;::,rir:  ;r .:..:;.\n"
	+ "        rr:,7iTzr:rz,:,rLcyc1;icrr;;rr;,;rL,: :nSrrcy,TjTr,:;.\n"
	+ "      rT7r;;rr;r:rijKWZc,yZbLL2KiZc.r;:r;;;.,Z2y;,:;.;U27r:rrc.:\n"
	+ "      :rrLn:,rZLrrTcOCr;;;1ZSSniS,:,r;:;r;, .;z:::,: ;KST,.:j7r:. .\n"
	+ "     1c,:;r;.,:r2i.jK;,;r88D@NjBG7ZbbG2iTcyKr;TT2ncTrnOyrBb8N1.,7r,.\n"
	+ "     .nT:,rzrrj1S$Ng@$D$@@@@@@@@08Gb88g80D@@@$@@@@@@@@@W@@@@8z.cGEr\n"
	+ "       ,,yE@Oj$$8g$@$$0D27yjiCEGWNOGGDD0B8GGKUSOSGbbUECGWCnZnz7U1r\n"
	+ "         .OC1r;.;17ZnrLENnrZrrEb8D$$@bzUG88B@$0b8WGGGGG7r17n2Cn1\n"
	+ "         c2crz;b@7    ,Dj;S@i :,,jL.nWD@8ULrDG1ZWbB880Oj.bT,.jr;\n"
	+ "      :r:,;.:.:;,  ..ri;,TW7T,r;jT: .By;,r7Eiz;:rrS,:;,;:,,:..;;.\n"
	+ "     .;. .rr.;,;1;1EWKr;,;:,LC::Oz      yS;;,...:rr:  yn7, ;r.   y7\n"
	+ "      :  .;.,,. :;rLKcrTZEOZ1znS$GGKjZbbGELLLZ7i2;r:::rc;;;r@8Z:.,c\n"
	+ "        ., ,UGn;:..,,rLnnr;12EWEZUEW8$8KjW;;rWOSi,Lrcn11;;rjBGzc:\n"
	+ "        Tr;LUGGSU1Z12E211z7yjz7jUyyc71zcTTjKW2jz7zU22KKnbjZKS;  .\n"
	+ "        ;ZcLrTrTT1n17iTz7nnZij7Zn117T1y7zciUjnyyTyTiTrczcz1SU\n"
	+ "         ,bWNOOCZ2CjKUUEbUSO8W8GGGGWNW8D8WGOGWN8$WOOWZOEbSWZ.\n"
	+ "          .;r7j21OEUbWEG88G8D0D0D$g$g$0$D0B8NB8B8NWbC2ZizT;.\n"

	, "                        .:,;;rrTLTLcrLrr;;::\n"
	+ "                   .,;rrTLzrcLcrcrcrTLTcyz77nTL;,.\n"
	+ "                .,;r;r;r;r;rrrrrrr;rrrrrrLrcLTT7y7zL;.\n"
	+ "              .:;;;,;;;;r;rrrrrrrrrrLrcrLrTrTczcTTyyiny,\n"
	+ "             .;,:;,,,;;r;r;LrrrrrLrzLTLcLTLzc7T7z1y7T17jnr\n"
	+ "             .,,;,;,;,;;r;r;rrrrTczczLycycyT7z1z1z7Tyy7TynL\n"
	+ "          ;CT,:,,,,;;;;;;LrrrcLyz1z7c7z171y1z1zyyyTyLTLzLcy,\n"
	+ "          rWW .,;,;;c;rrzLyzz7nyn1n7n7n7i7n1ny7z7zTTTrrrcrT;\n"
	+ "           ,,;,;;;;;;;;1T17yyicy7injni1j1n1izny7cyTTrLrcrr;;.\n"
	+ "             :,,:rTrnLc:,,rrL:;rcLzLzrcccrcrcrTLyz1rcrr,,rL;;\n"
	+ "            ;7cEWG8O2GWL;n;  :,,.. :L; .:;,;;;;r,:.,.   .rrrzn.\n"
	+ "     .r;,r;Ty;T7bbKrry2SS7zzK8$8r:LrUgD;ZD8GcTZ2Er;;,.,r;rjz;;:\n"
	+ "     cUZTbGnzncrL7rrrWW8WO88UWNg8$$Sr7bEW0jS1n7nEW2r:;TKyyzc,ZCc;;\n"
	+ "    .r;,;zCcin1rr;;cjyT7bWWGNOWSNGD@n7W2KUbUb2bU2KUyr:cn80i;TGKLz;r.\n"
	+ "     ;r1EU7j7Ec;cLj0S;,LnZjEWWWC2UnnnGGOOGKCGDUz2CUb2CL,.W2y2gcTTLr;\n"
	+ "      .rrrySG2rK2ZN1,1Z;L77O;rr7Er.,;:.,Lji;KUrzUZSn;r;,,ZE;ZL,.:\n"
	+ "           .;;rr1SjjiWS2rrc81::r,:rr.r;.;7:cEU2WZEc,:;;;;,,.\n"
	+ "              .;r;rTjiZjGE.LSir;;1ZnnEWT::,;2CnzyLr;;:....;,:..\n"
	+ "               ,;rrr;;,;,;,;;ci1LKC2iEjL;zLir;,,:,.::;;rrcr;,:..\n"
	+ "                :;Lrzz1zTrcrcrrrLrLrLrcrcrr;;;;,;;rrLLzLL;;::..\n"
	+ "                   :,rryzi7jnCjCiZninjnj1iyyTyTyczLcrr;,.:.. .\n"
	+ "                        ..:,;;rrcc77n7nz7zzrrrr,,::..\n"

	, "                                     LLLL:.\n"
	+ "                                    LL,,:;;L,.\n"
	+ "                              .:;;L11;;,;,;;L1C:.,;,;:\n"
	+ "                       :,;;LLLLL;;;;,;,,:,,;,,;LLLLL1CLL;,\n"
	+ "                ..;;LLLLL;;,,:;,,,,:,:,,,:,:,:,::::.:.,;LLLLL;,:.\n"
	+ "         ..,,LLLLL;;;;,;:,,,,;,,:,:,:,:,:,:,:,:,:,:,:,::.:.:,;;LLL;L;.\n"
	+ "    ,;L;;LL;;;;,,:,,;,,:,:,,,:,:,,,::.::::,::.::::,:,,,;;:,::.....,LG8\n"
	+ "LtC80CLL;;.....::::,::.:::.::,:,:,.,.:.:.:::.:.:.:.:.:.:.....,,;;Li1CG\n"
	+ ".;1G@CCCt11L;,:.....,::.:.,.:::.:.:...........:.:.......:,;;LLtt1LtLG;\n"
	+ "    ;GCGCCtCtt1LL1L,...:.:.......................    :;1LLL11tLLLLLC1\n"
	+ "      :;Lii11iCLCG;.. ....:...... ... ...   .     ..;iGC11;L1ttLL1G8L\n"
	+ "        .CGCtii110tL,: . ......... ..  ... .   ..:;iLGC8G8Gi1111L11Ci\n"
	+ "    .;LL1LLLL,;;LCGCCL,..       .     . .   ..:;1tGGCGGG8GtLLLLL11CC;\n"
	+ "    :8t1,,:,:,,,:LGCCG11;:..   .          .:,L1GGGCGCGGGCCtCtCtCCC;.\n"
	+ "     L0CGL:,;,;,,.1GGCCCC1CL: .         ..;LtCGCCCCCCCt1111LLLLLL;\n"
	+ "      G1CGL:.::;,,;LCGGGCCGL,.         ;LtCGCGCCtCCCL;;;,;;;,,,;;L\n"
	+ "      L8t10L,.::;LL;,LCGGCG1L,     .;;1CCCGCCCCCCCCGC:LLLL;;;;;;L;\n"
	+ "       .,LC8@1.;;;;CL::,tG0GCtL,,;;LLLtCCGCCCCCGCGC1,,,;;L;;;;;LL;\n"
	+ "         Lt1CCLL,  ,11;LLL00tCC11L;:L1CCGGGCCiC1L;,.:::,;;;;L;LLL\n"
	+ "            .Ci80t.  ;L1L;18Gt1LLL;LtttCC1;,,,:;;LL1;,:;;;;L;L.\n"
	+ "             :L;LG0C;  .;;;1@0G111ttCCtiL,LL;;;;LL;11,L;;;;;L.\n"
	+ "                :11C88L   .:;CGGGGiL;L;L;;,L;;;;;;::;L:;;;L1.\n"
	+ "                  . ,C001     ..,;;;;;L;L;;;;:;;LL1tG8GtiC1\n"
	+ "                     ;;i0@G;       ....:.. .;Cit1LLLLCC1;.\n"
	+ "                    .;,.:;G0GL.           :;t11LLLLL1,.\n"
	+ "                      .. , .LGGL:..;,,:;LCCCGGLL,LL1t\n"
	+ "                         :t1;:t88GCL;CC11L1t1:1tLL: :\n"
	+ "                           LGL:LLL1; ;;:       .\n"
	+ "                            GC1;;L:.:\n"
	+ "                             t111L\n"

	, "                                ..::.  .,.:,,:.\n"
	+ "                 .:;;L1CCGCGG08000800GG000808GGCCt1L;;.\n"
	+ "          .:,,L1tCGGGGGGGGCGGGGGGGGGGGGGGCGGCCCtC1111LLLL;,\n"
	+ "       ,;LL1LLLL1tCCCCCGGGGGGGGGCGGGCGCGCGGGGCCCtC1LLLLL;;;L.\n"
	+ "      LL;;L;LL11tCGCCGCCGGGGGCGCCCCCCiCCC1CCCiCCCCG1tLLL;;,;;\n"
	+ "      ;;,;;LLCCCCGCGCGGGCLtCCGLL;1C08G800C;CCLtGCt11tCCCCCLL;\n"
	+ "      ;;L1CCC1L;1G8G800G@880@@@@@@@@@@@@@@@0@000GG0C1tCLCG0GC\n"
	+ "      .8GLtCt;LCCG@@@@0G@@@8G8GGG8GGCGG00@@@0G00CCG0808C1L;t1;,.\n"
	+ "        ;LLtL;tG8GGCG1LLL;;;L;;LL,LLL,,.,;LLG0@@CLLtCG0C11GG1;,:.\n"
	+ "     ;:  :L1iCC80L ;LtC80@@@@@Lt:.LG@@@@0G1, .1GGGGGCCCt;,,:  .,.\n"
	+ "    LLLC1L880G00@L    ..,,;;1;LGC,:.::LLLLL.   .1C1;:;:..:    .,\n"
	+ "    :L,,;11t1ttC81.. .        ;L,L11C;;L;;;;:....        LiL:: :.\n"
	+ ".,0.,L. L1CGGG0GtG@@@CCC8CL1t;C8iC@@8tCCC1LLL;;;;;LL1LLLL1ttCGG;10i\n"
	+ "GGGCCLLCCCLCG0@L.CLG0L00C8GG08C08GGCtLL,C8800G8@0000tCG0G0LL1GC;;811.\n"
	+ "  L:1CGG8GG1itGCGL:0800CCCGG@Gt@8L@t;LLiG00@8,ttCC8CLt0G@01t@C;;11Ct.\n"
	+ "    :GLCLLGC1GG@t;LCC88CC000G00@G;iGGG.0GC,1LL@C1GtLL; .LLLC1CL1;\n"
	+ "       ;LL11CtCG880GCC0L108G88880CC0@G Lt1C1CCGGGCCCGtL1iLLLL18,\n"
	+ "       LLLL1tCCCGGGGGGGGGGGGGGGGG08GGGGGG8GGGGCGCCCCCCCt11LLLL\n"
	+ "      .1t1tCGGGGGGGGGGGGGG8GGG8GGGGGGG8GGGGGGGGGGCGGCCCCCtCtC;\n"
	+ "       .L1CG80@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0@0088GCC1,\n"
	+ "              ..::;;L;LLLL1L11tit1tit1i11L11LLL;L;;::..\n"

	, "                             ...,;LLLLL1tt111L;,:.\n"
	+ "                        .;;1L11LL11111L1LLLi1i11L111L;:.\n"
	+ "                    :;LLLLLLLLLL1LL1iL111Lt1tL11L1t111tiiL,\n"
	+ "                .,;L;;,;;LLLLL11L1L111111t1i1itti111111t11ttLL.\n"
	+ "            ..,;;,;;;,;;LLLLLLLLLL1L1LLL11111L1L1L1L1L1LLLLLL1t1L,.\n"
	+ "           ,,;,,:,:,,;,;L1LLLLLLLLL1LLL1111111111111it1111LL111i1Ct1L;\n"
	+ "         .::::::,:,,;,;;LLLLLLLLLL11t1itCCCCCtt1111LCtt11L1L1LLLLLLL1itL.\n"
	+ "       .::.::,:::;,;;;;L;L1L;LLL;LL11i11LL111L;:.;;;;L;;;;;;;;;;LL,L;;;1L.\n"
	+ "       .::::,:,:,.:,;LL,;;;;1;: .:.           ;LCC8tt;,L1i1L1C@@@@8,..:.:.\n"
	+ "       :.:.::;,;;CC1::.. .;188880@0G1LLC11LLL1C0@@@@08L..;;L;;;;,,,,;L.\n"
	+ "        ..;,:.,:;1;    .1G@0@GG0@@@@@@@@@@GCL1@@@0@0@@GGGCL.... .:;;L;;..:1tL.\n"
	+ "        ,1t, ..      :C8GGGG0@0t;LCGGGtL,::t8tLL,.L1tCiGG00888C1L;,..:LCC8@G.\n"
	+ "  .  . ,iCt...,.   ,G08CCG0GCG008CCttLLLL1C88CC80GCLL.   ...LtGG8GGGC;CGC1G@:\n"
	+ "  ;L...:..;1;: .:iG01. ..:LC0@GCtGG0@@@@8@0000GC,.     :;;:  ,:;1CCCG08GGC;1\n"
	+ "   ....    .L1CG81;   ..Cti:;CLGC1LLLt8@@@@GL.      .L0@@@@@@01LLLL;L@@88L. .\n"
	+ "  :;.:,....  .,:     :LLt00t1L:C@0GC11;;;C08L.       G@@08G@@@@0GGGCLL;CtL,,:\n"
	+ "    ..;,         :,.. ;tCC8@@0G1G@@@0GG00tLCG8G1L;;:..::;L1ttLLLLL;;LL,  .;;\n"
	+ "     .  ,. :...: ,;;.,,;Ltt08CCC1LL@@@0GGGG8GGCGGGtCGC11CC11;;LLLL;;;;,;;LL1.\n"
	+ "      . ;. :;;L;L;;;L;LLL;;;;;L;;,;,;;;,,:,:L;;;;L;LLL1LLL1LLL11t1111LLLLLLL.\n"
	+ "      .   .,,;,;;;;;,;;;;L;L;LLLLL;LLLLLLLLLLLL11111L11tit1111L111LLLLLLLL1L\n"
	+ "       .  :.,:,,,,;L1LL;;;L;L;LLLLLLLLLLLL1L111L11i11iC1t11LLLLLLLLLLLL;LL1.\n"
	+ "       ....:.,:,,;;;;L;;;;;LLLLLLLL1LLL1LLLLL1L11iL1i1LLLLLLLLLLLLL;;L;LL1:\n"
	+ "         .::,:,,;,;,;;;,;;;;;;L;LLLLLLLLL;LL1L1L1LLL1LLL1L1L1LLL1LLLLL1tt:\n"
	+ "           .:,:,,;,;,,,,,;;;;LLLLL;LLLLLL111L1LLLLLLL11iL1L1LLL1LLLttiL,\n"
	+ "              :,;LLLLL111111t1tiCCCCCCCtCCCCGCCCCCGCGCGCGCGCGGGGG8GtL.\n"
	+ "                     ..:.,:,,,,;;;;LLLLL;LLLL1LLLLLL;L;;,;,,:,::..\n"

	, "                               :, ..\n"
	+ "                     ,:LLL;  ,,,,L.,;,:.:;;,.\n"
	+ "               .;L1LtGC1LL1L1C1LtCtttCCiCCCCCC1   .\n"
	+ "             LLL1i1tCL;L;LL11LtGt1tCCCCti1L1L;;1L1CC1LL;.\n"
	+ "          ,L111111LLCLL;111LCCC1Ct1tCCCGCtCLL;ttCCCCCt1111L.\n"
	+ "         LCi1L11L1;CCL:LL11i1i1CCCCCtCitC1LLLCGCCGCCGGCCCCLL.\n"
	+ "       .tti1LLLLLLLtC;;;LLLLi111CiCCC11L1LL1CCt1GCtCCCCCCi1Li,\n"
	+ "       C111LL1L;;LL1t1;LLL;LLC1L111CCCL;;1CC1CtCCCCGCGCCC1L;L;.\n"
	+ "       LCLL;L;;,;,;L1;LL;,LLLLLLtL11CLLtLiCttiCCCCCtCCCCttiLL1L\n"
	+ "        .1ti11;;:,;L;;,,.:,,;L,LCiLLLL1t1t1LL11i111111L111i1LL\n"
	+ "      LLC08GGC80@000GGGtCC1L1itCC1t11L1L1111111L1LL111CCtii;:\n"
	+ "    G@@GL;,1;10@@@@GCCtCC@@@@@GGGGG80@@@@0808GG0@@@@@00Gt1C800;\n"
	+ "   ,i1GL,.,C880GCL;:;LL1G08C1;LLLLCG800Ci1C1t8@@@@0GCit11C@@G11LCtL\n"
	+ "   ,L,:,,LLCGCLL.. :;tG08G1L1CtLC088Ct;,;;:1G0008GC1LLL1G8GGLLLLL1GG;\n"
	+ "     ,,,;;,.;..:; L,::LL;,LLiLL;LL1LL,;;L,;;LLL;;;;;L;;,LLLL1LLL1CCL.\n"
	+ "    LC;1L;.....,..;,   .,;:,:,,;:,11LL;LLLL1;L;LLLL11CGGCGGGGGL\n"
	+ "   ;GGCC8GC1L;L,,...,:,:.,;LL:;;L;L1CCCC808GGG000808080GGGGCCL11;\n"
	+ "   11CGLLttCCGGC1i1i1tCGG00@000@@@G0@8G0GGGGCGCCCGCGCCtt1ttC1C8@G:\n"
	+ "      ;tGCCi111CGGGGGCCCG8GG00@G0GCG11CGtG@GGGGGGG8GCtG080@8CG00;\n"
	+ "       LCCCGCGGGG1GG@@@@LCGGiG0itCGGCCCCi@8808GCCGCCG0C8G8G8GCC;.\n"
	+ "        LL1CCtC1ttGGGG8GCGG8GGGt8GC0@@@@0GCCG8GCG8GGiG8CGC80C.   ..\n"
	+ "         ,LLLL;;;L1tLtt11LLiL1C0CCGiGGCGGGCiiGCGGGGCCGCCCGCi.  ...\n"
	+ "           .;LLLLL;;LLLLLLLL1L1CttCtCtt1ttt11tCiCCCCGCGCCL:   . .\n"
	+ "               .,L;L111t1t1t1i111titt11ttCttCGCCCC1L;,.\n"
	+ "                          ..::,:,:,:;,,::..\n"

	, "                            ,,LL1L1111L;;:\n"
	+ "                        .;;LL;;L;;;;,,;LL1LLL,.\n"
	+ "                    ,,;LC;L,,,;:,:;,;,;;,;;;LL1LL;.\n"
	+ "               ,;LL1LL;;,;,;;,,;,,;;,L,;;,,;,;;LLL1LL;;.\n"
	+ "           :LLLLL;;,;,,:;;;:;;;,;,;,;,;,,:;,::,,,:;,;L111L;:.\n"
	+ "     ..,;1;LL;,,,;:,,;,;;::;;;::.,,.,,.,:,,,,,.,:,;;:;,;;LLL11LL;..\n"
	+ "    1;;;;;,,:.,,,,;,;,,,;;,,;,,;L;;,;LL.,:,,;,;,;;L,,:,:;,,,;;LL1LLL1,,.\n"
	+ "   :G1;:::.,:;:,:;:,,;;,,,:;,;;L;;,;LLL;,;;;:;;;,,:,;;:,:;:,,,,:,L;;;;;LL;.\n"
	+ "    GCG1L,..;:..::,.,,,:;,;:;,;,;,L,,:;;;;,,;;;;;;;,;;;::,,,,::,,;;,;,:.,;t\n"
	+ "    GCCGGGGt;,..  ..:,:::,:,;,::,;;;;;,;;;;L,,,;:;,,:,:,,,:,;;.;:,.,:,L1tGGL\n"
	+ "   L1CGCCCGGGGGCCL,.. .,::,:,,;,,:,:;,;:,,;,;:,:;:,,,:::;::::::,,,L1tCCCCC8G\n"
	+ "   . ,tG8CGGCGG888GC1L;;,. ..,,;.,,;:::,.::,:,;;,,:;,::,::,;LLLCtCtCtCtCtL;.\n"
	+ "        ;LG88GG8GCGCG08ttL;;;.:...:;,..:::::.:..,:.:..11L1CGGCCCCitttiCtL:\n"
	+ "   L;;:.   .;1C08GGiCGC1G8CCGG11L;,,:,.:...:.,:,;LLtiL;11t1CtC1CC1iGGG1,L1C1\n"
	+ "   L1;LLLLL,.   ,LCCGC0GGCG1G88GG88CGGGGGCGCCGGC8GGtC1;CC1iCCCG111GG1:.LCtGG:\n"
	+ "   ;GL,;;LLLLLL;::.,;LLCGGG8GGGGGGCGGGCGGGGGGGCGCCCCtCL8GGCC1LLL11L:.;tGCCC0,\n"
	+ "    LGGL,:,,LLLLLLL;;:...:;L1CCGGG8GGGGGGGGCGCCCCCCCC1LLLLL;LL1LL..LCGGCGGG;. .\n"
	+ "     :10Gt1L;,:;;LL1L111L;:.    :;LCCGGCtCCCtGCCCGCCi1L1L1LLL;::,LC0GGGt1;.  .\n"
	+ "       L0@@@0GL;;,,:;;LL11CCCt1;.       LCGGGGGGGCtL1LL;;,,:,;1CG8GCt;,\n"
	+ "         ;1G8@@@00GC1L;;,,:;;LL1ii;   .it1LL;;,,:::,:,,;LLiGG008G1,.   .\n"
	+ "            :;1CG0@@@@000CC1LL1LLL111L1LL;L;LLL1tCC1G88G888GGtL,: . .\n"
	+ "             ...:;L1tGG0G0@G88GGC8iGG88G8GCGG8G8CGCCGGCCLL,:.. .\n"
	+ "                ..:.::,,,LCC8C080008088G8GGG8GGGGG8t;:... .\n"
	+ "                     ..:::.::,;LLttCGGGGG88GGGCCCL,. .\n"

	, "                          .:,::,,::.::,:,:,,,:,,;:,,;:;..:;;;\n"
	+ "                      .::,:,::::...........::..,.:...    ,LL,:\n"
	+ "                  ..::,.......... ........:.,.:::..  .;LtLL;;,\n"
	+ "             ..,,,:,:... ... ....:.......:...... .:;:CGGC1L,;1\n"
	+ "       .:.,,,:,.:........ ........:.....:....  .:,iL1CGt1;;,;L;::\n"
	+ "   ..::,::...... ............:.......::.     :,LLLL1L80C1L;1,L;;,:.\n"
	+ "  .:... . ... :.... ..:.::,::.: .       .,;Lit1CG1LLtCLLCCC:\n"
	+ "  .;.:.....:.:...L. :....;.. ..,;;,;;L11LCCCGC;tCiLiL1GG1C1\n"
	+ "    ..:.:..... .,  :,. ;t: .,LL1C18CCCCCCLCtGCL;GC1LLCGLLC.\n"
	+ "       ..,,;;1;;;, :..  ,;:.,;LLLCCCtC1tCCt1tC11i1,L1CtC1: .\n"
	+ "          .,1tCG@0C:;;;,:.L: .;;;;;;iiCCCt1L1CGGG8GCCC1L;.LLL..:,.\n"
	+ "             :;LttL;,,LCCC881CGCCCLCCC1;,;1GG@0@@8GGCL,;;L;..;tGL,:.\n"
	+ "              .:;,;;,,;:;;L1CtCCCLLL;...LCG80000@0GCC1LL,..;CCGCLL;:.\n"
	+ "              .;,;L;,;;L;;,;,,::..:,:L1GG000G8GGC8GC1CLL;;L;,0G1L1LLL\n"
	+ "               .;;,.,,;::.::,,;LCGGG00088GGCGGGGC11CG: ,0Gi;;CtLL1ttL\n"
	+ "       ..,:.     .   . .LLL1LLC08GG8GGGCCGCGGGGGt1L :CL0@GCGCLL1tCiL\n"
	+ "        :.;;L;:.    .  ;iLLLLtGtCtCCCCGCCCCt1LL;, ,,LC8tCG00GC1,LL.\n"
	+ "          .,LL;;LL::...LLLLLL11111L1LLLL;;,,::.. :,L,..LLCGCLL;L.\n"
	+ "             .:.:,;;;;;;;:;;L;;;L;;,;:,::::.:. .;;tCCLL8CiL;t1G.\n"
	+ "                 ..::;;;,.   ::,,,:,:,::.:..  .;;C0080GC1L;GCi1\n"
	+ "                    ::::;;;::     ..:......   ,;LG@GC1111iGG;\n"
	+ "                     ..:.,;;LL1L:.          1C;L1C1LL11CCC1\n"
	+ "                          ;:;t1L1LL;:      18GG1t11tCCGC,\n"
	+ "                            ,1,,,,LC1ttt;,1GCGCCC800Ct,\n"
	+ "                              .;LL1iCCGGG80GGGGGGCL:\n"
	+ "                                     .:: ,:.\n"

	, "                                          .:L;L;;,;:LL\n"
	+ "                                      ,LLL,:::......:,1.\n"
	+ "                          .   :,LLL;,:::: :::.:.... :.:L\n"
	+ "         ..,.:,:..:;;L11LLL;:,,;:,,:.........,::.... ..;L\n"
	+ "        L1LLL;,;,:,...:....:;,,,:.::;,;,:.. .::....,,. .,L;\n"
	+ "        ;1;:.,. .;;;;;::;;,;L1;L;;;;;;;;:::,,;,L: .:,:.: .;i:\n"
	+ "         ;L;;;::;;;:L;;,;LL,;;;,;,;;;:,;;LL,,:::,:,::.::..,;;\n"
	+ "         LLL;,::.,,,;:,LL;;::::,;;;;:;,;;L;L11LLLL;;::::.  ..Li,\n"
	+ "      ,L,:Ct;LL::,;;;;;;;.,;,;;,;;;,,;,,;,;:,,;:;;;,,,;:...     ,\n"
	+ "       iCt1..LL,;;,:;L,L;;,;:,:,:::;LL:,,,,,,;,,... .,::,;.:.   .:\n"
	+ "       ;t.  .GGCL;,.;;;;L;;,;,;;;,::.;LLL;;;;,;;;,;,,:::;.,.:..   ..\n"
	+ "        .    CCG8CL;:;;,;::::,,  :,::;:;,,..,::;;;,:,:.:,... ... . ..\n"
	+ "             ,GG80C::.;;,,:.:.,,: ..;;;.::;L;.;,;;;.:....   ... ....,\n"
	+ "               LCG@8;. ::,,,,..;..,;,,.:.:,;:. ... ... . . ... ..:. ..\n"
	+ "            ,,:    ;1L;.L;:,;:,,;,:  ....   ..... .   . .    .,:.\n"
	+ "          .LL1L; :L8t;  .  :...... ....... ...       ..:.:,:..   :,Ci\n"
	+ "          LLLL1LtCC;  ,:L;,:;;;:::,,,,,::::.:.:.,,,.:::.::,:::;C8CCG0G\n"
	+ "         ...,LLC1;     ;L1LL;L;;;L11LLLL;LLLLLLLL1LL;L;L1CCG8G8@; L@G8\n"
	+ "              ..,  .;;. .;11tCGCCCCCCCCtt1i1111it1itiC@@@@@CCCGGL,t8C.\n"
	+ "                   ;;LLL:  . .:C0t;;,;;LLLLL;LLLL;...C0t.;1G ..LC::;,:.\n"
	+ "                    ;1tLtCGG0G1.   ..     .,L1t1CCt. .L1   L:  ,LL;:.\n"
	+ "                      ,L1LLCtG@0L ..  .;L;        .,..;1,.,L1i1L:.\n"
	+ "                       .LLttL:,1GCi;. LtttC1111L11i11111ti1;;,.\n"
	+ "                         ;1t11LitGGGGGGCtCtttC1111LLLL;,..\n"
	+ "                            :LLLL;;LLLLLL;;;;,:\n"
];


module.exports = function() {
	return sandwiches[Math.floor( Math.random() * sandwiches.length )];
};
